package knowledge

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type SearchResult struct {
	File    string `json:"file"`
	Line    int    `json:"line"`
	Content string `json:"content"`
}

type FileManager struct {
	projectDir    string
	knowledgePath string
}

func NewFileManager(projectDir string) *FileManager {
	return &FileManager{
		projectDir:    projectDir,
		knowledgePath: filepath.Join(projectDir, "knowledge.md"),
	}
}

func (fm *FileManager) InitKnowledge() error {
	if _, err := os.Stat(fm.knowledgePath); os.IsNotExist(err) {
		return os.WriteFile(fm.knowledgePath, []byte("# System Knowledge\n\n(Auto-generated by DSMB-Agent)\n"), 0644)
	}
	return nil
}

func (fm *FileManager) ReadFile(relPath string) (string, error) {
	clean := filepath.Clean(relPath)
	if !isAllowedPath(clean) {
		return "", fmt.Errorf("access denied: path outside allowed directories")
	}
	full := filepath.Join(fm.projectDir, clean)
	data, err := os.ReadFile(full)
	if err != nil {
		return "", fmt.Errorf("read file error: %w", err)
	}
	return string(data), nil
}

func (fm *FileManager) SearchCode(directory, pattern string) ([]SearchResult, error) {
	clean := filepath.Clean(directory)
	if !isAllowedPath(clean) {
		return nil, fmt.Errorf("access denied: path outside allowed directories")
	}
	root := filepath.Join(fm.projectDir, clean)
	var results []SearchResult
	filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(d.Name(), ".go") {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return nil
		}
		lines := strings.Split(string(data), "\n")
		rel, _ := filepath.Rel(fm.projectDir, path)
		for i, line := range lines {
			if strings.Contains(line, pattern) {
				results = append(results, SearchResult{
					File:    rel,
					Line:    i + 1,
					Content: strings.TrimSpace(line),
				})
				if len(results) >= 50 {
					return fmt.Errorf("max results reached")
				}
			}
		}
		return nil
	})
	return results, nil
}

func (fm *FileManager) UpdateKnowledge(content string) error {
	return os.WriteFile(fm.knowledgePath, []byte(content), 0644)
}

func isAllowedPath(clean string) bool {
	return strings.HasPrefix(clean, "internal") ||
		strings.HasPrefix(clean, "ai/") ||
		clean == "ai"
}
